gaming:
  # 為 grayscale 2 為 測試模式
  template_matching_mode: 1

# 選擇地圖
quickly_choice_map: Hunting_Ground_I

# 設定的地圖路徑
map:
  test_map: "img/monsters" 
  Hunting_Ground_I: img/map/Hunting_Ground_I
  Pig_Beach: img/map/Pig_Beach
  Victoria_Road: img/map/Victoria_Road
  Kerning_City_Middle_Forest: img/map/Kerning_City_Middle_Forest
  Mushroom_Garden : img/map/Mushroom_Garden

mini_map:
  Mushroom_Garden : img/mini_map/Mushroom_Garden/Mushroom_Garden_1.png
  Hunting_Ground_I : img/mini_map/Hunting_Ground_I/Hunting_Ground_1.png