#怪物匹配過濾器
# [1] 中心距離閾值過濾器 :pixel_distance_filter [2] 非極大值抑制過濾器 : NMS

mob_filter_method:
  method : pixel_distance_filter

nms_threshold : 0.4   # (0-1) 數字越高判定越嚴格，怪物越；數字越小，越容易把複數重疊歸納為同一隻
pix_filter_threshold : 50  #（像素） 中心距離閾值：兩隻怪物中心點小於此距離時，會被視為同一隻怪物的殘影並過濾cls