
game:
  title: "新楓之谷：經典版"

player_setting:
  #喝水設定 key:按鍵 Vale:觸發血線，低於就喝對應藥水
  #常用按鍵 "delete"
  health_setting:
    light:
      key: null
      value: 80
    medium:
      key: null
      value: 50
    critical:
      key: "delete"
      value: 20
  auto_control_config:
    #人物的攻擊範圍(像素)
    attack_range: 100
image_processing:
#圖像匹配度設置，抓不到怪物或角色，在這邊調整過濾程度
  
  #怪物匹配最小值
  mob_min_threshold : 0.7
  #人物匹配最小值
  role_min_threshold : 0.6

game_bot:
  #roi範圍的位移量 ，要在減少運算/加大偵測怪物範圍間取捨
  roi_x_offset_l_width: 100
  roi_x_offset_r_width: 100
  roi_y_offset_t_high: 100
  roi_y_offset_b_high: 50

auto_control_config:
  #沒怪時左右尋怪 True/False
  search_interval: False
  #邊界距離緩衝//確保人物不會時常觸發返回平台 單位:像素
  buffer: 15
  
  #這是平台判定的偏移量，有些特殊地圖，平台Y軸落差很大時再動，否則預設 "5"像素
  platform_offset: 5
health_detector:
  #存放血條的是窗內位置 list[x1,y1,x2,y2]
  hp_lect: [504,755,608,766]
  lower_hp_color: [0, 200, 200]
  upper_hp_color: [5, 255, 255]
  # mp_lect:

keyboard:
  #QWERTY
  left: left
  right: right
  attack: ctrl
  pick_up: z



folder_path:
  template_nametag_path: img/nametag/example.png
  my_character_template_path: img/nametag/MyRoleNameTag.png
