
game:
  title: "新楓之谷：經典版"

player_setting:
  #喝水設定 key:按鍵 Vale:觸發血線，低於就喝對應藥水
  #常用按鍵 ''delete"  "page down" "page up" "end" "home"
  health_setting:
    light:
      key: null
      value: 80
    medium:
      key: null
      value: 50
    critical:
      key: "delete"
      value: 20
  mp_setting:
    light:
      key: null
      value: 80
    medium:
      key: null
      value: 50
    critical:
      key: "pagedown"
      value: 20

  #戰鬥設置
  auto_control_config:
    #功能:鏢賊跳射(跳躍攻擊) True:打開 False:關閉
    is_Night_Lord: False

    #人物的攻擊範圍(像素) 參考: 近戰:100-150 遠程:200-500 
    attack_range: 130


image_processing:
#圖像匹配度設置，抓不到怪物或角色，在這邊調整過濾程度
  
  #怪物匹配最小值
  mob_min_threshold : 0.9
  #人物匹配最小值
  role_min_threshold : 0.6

game_bot:
  
  #roi範圍的位移量 ，要在減少運算/加大偵測怪物範圍間取捨
  #參考: 近戰 100-200 遠程 300-500  
  roi_x_offset_l_width: 200
  roi_x_offset_r_width: 200
  roi_y_offset_t_high: 110
  roi_y_offset_b_high: 40

auto_control_config:

  #尋怪功能開關 True/False
  TOGGLE_PATROL_ACTION: True

  #打怪功能開關 True/False
  TOGGLE_COMBAT_ACTION: True

  #允許進行平台移動的時間閾值:單位(秒) ； 若間隔時間內沒有怪物，進入移動狀態
  find_mob_time_threshold : 12

  #人物卡住檢查間隔時間:單位(秒); 巡邏狀態中，超過這個時間，觸發防卡頓動作
  stuck_check_time_threshold : 3

  #邊界距離緩衝:單位:像素;確保人物不會時常跑出打怪平台 
  buffer: 3

  # 跳躍距離閾值，太遠容易抓到很遠的跳躍點(有可能頻繁卡住)，太近又容易偵測不到
  JUMP_DISTANCE_THRESHOLD: 15 
  # 跳躍點範圍;大小會影響偵測跳躍點時的判定。
  ACTION_POINT_RANGE : 2

health_detector:

  #健康條的座標；解析度、DPI設定都會影響判定範圍，若發現判定不準，需自行測量範圍
  hp_bar_loc : [503, 751, 608, 754]
  mp_bar_loc : [611, 751, 716, 754]
  #血條顏色範圍
  lower_hp_color: [0, 200, 200]
  upper_hp_color: [5, 255, 255]
  #藍條顏色範圍
  lower_mp_color: [100, 132, 238]
  upper_mp_color: [107, 255, 255]

keyboard:
  #鍵盤按鍵設定
  left: left
  right: right
  up: up
  down: down
  attack: shift
  pick_up: z
  jump: alt



folder_path:
  template_nametag_path: img/nametag/example.png
  my_character_template_path: img/nametag/MyRoleNameTag.png
